### ISSUE TITLE
AttributeError: 'module' object has no attribute 'cv'

### ISSUE THREAD

**Issue by yeLer** [YukangWang/DeepFlux#2]
I have installed opencv3.4.3,when run the train.py i get the Traceback... Could you help me look it

Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import cv2
>>> print cv2.__version__
3.4.3
>>> exit()

Traceback (most recent call last):
  File "train.py", line 279, in <module>
    train(args.initmodel, args.gpu)
  File "train.py", line 258, in train
    solver = caffe.AdamSolver('solver.prototxt')
  File "/home/disk/yeler082/DeepFlux/examples/DeepFlux/pylayerUtils.py", line 46                                                                                      , in reshape
    self.image, self.flux, self.dilmask = self.loadsklarge(self.fnLst[self.idx].                                                                                      split()[0],self.fnLst[self.idx].split()[1])
  File "/home/disk/yeler082/DeepFlux/examples/DeepFlux/pylayerUtils.py", line 98                                                                                      , in loadsklarge
    dst, labels = cv2.distanceTransformWithLabels(rev, cv2.cv.CV_DIST_L2, cv2.cv                                                                                      .CV_DIST_MASK_PRECISE, labelType=cv2.DIST_LABEL_PIXEL)
AttributeError: 'module' object has no attribute 'cv'

**Comment by YukangWang** [comment]
Sorry for this. Please use `cv2.DIST_L2` and `cv2.DIST_MASK_PRECISE` instead. Because our experiments are based on OpenCV 3.4.3 (C++) and OpenCV 2.4.9.1 (Python).

**Comment by yeLer** [comment]
I get it .Thank you very much!
