### ISSUE TITLE
RuntimeError when running train.py

### ISSUE THREAD

**Issue by CharlieLeee** [YukangWang/DeepFlux#3]
Hi, Thanks for the great work!

I ran into this error when I was trying to train scripts in my Ubuntu18.04 python3 environment, any idea why this happened? Thanks!

 command: python3 train.py --gpu 0  --dataset sklarge --initmodel ../../models/VGG_ILSVRC_16_layers.caffemodel

Traceback (most recent call last):
  File "train.py", line 283, in <module>
    write_net(args.dataset)
  File "train.py", line 107, in write_net
    net.sdcrop = crop(net.upsd, net.relu3_3)
  File "/usr/lib/python3/dist-packages/caffe/coord_map.py", line 178, in crop
    ax, a, b = coord_map_from_to(top_from, top_to)
  File "/usr/lib/python3/dist-packages/caffe/coord_map.py", line 168, in coord_map_from_to
    raise RuntimeError('Could not compute map between tops; are they '
RuntimeError: Could not compute map between tops; are they connected by spatial layers?

**Comment by YukangWang** [comment]
Maybe you're using the official Caffe. Just append `'Concat'` to `PASS_THROUGH_LAYERS` in the file: `caffe/python/caffe/coord_map.py`.
