### ISSUE TITLE
Undefined variable $thr in eval_py.sh

### ISSUE THREAD

**Issue by ekincanufuktepe** [YukangWang/DeepFlux#4]
In `DeepFlux/examples/DeepFlux/evaluation/eval_py.sh`, where `python ../inference.py $deploy $model $gpu $imageDir/ $thr $dks $eks $detDir/` is executed, there isn't such variable defined as `$thr`. I think instead of `$thr`, it should be `$lamda`.

**Comment by YukangWang** [comment]
Yes, it should be the same as that in `eval_cpp.sh`. Thanks for pointing it out.
